--5-1
SELECT *
  FROM EMP;
  
-- 5-2
SELECT *
  FROM EMP
WHERE DEPTNO = 30;

--5-3
SELECT *
  FROM EMP
 WHERE DEPTNO = 30
  AND JOB = 'SALESMAN';
  
--5-4
SELECT *
  FROM EMP
 WHERE DEPTNO = 30
  OR JOB = 'CLERK';
  
--5-5 곱셈 산술 연산자 사용
SELECT *
  FROM EMP
 WHERE SAL * 12 = 36000;
 
--5-6 비교 연산자
SELECT *
  FROM EMP
 WHERE SAL >= 3000;
 
--5-7
SELECT *
  FROM EMP
 WHERE ENAME >= 'F';
 
--5-8
SELECT *
  FROM EMP
 WHERE ENAME <= 'FORZ';
 
--5-9
SELECT *
  FROM EMP
 WHERE SAL != 3000;
 
--5-10
SELECT *
  FROM EMP
 WHERE SAL <> 3000;
 
--5-11
SELECT *
  FROM EMP
 WHERE SAL ^= 3000;
 
--5-12
SELECT *
  FROM EMP
 WHERE NOT SAL =3000;
 
--5-13
SELECT *
  FROM EMP
 WHERE JOB = 'MANAGER'
    OR JOB = 'SALESMAN'
    OR JOB = 'CLERK';
    
--5-14    5-13과 동일한 기능을 간단하게 IN연산자
SELECT *
  FROM EMP
 WHERE JOB IN ('MANAGER', 'SALESMAN', 'CLERK');
 
--5-15
SELECT *
  FROM EMP
 WHERE JOB != 'MANAGER'
   AND JOB <> 'SALESMAN'
   AND JOB ^= 'CLERK';
   
--5-16
SELECT *
  FROM EMP
 WHERE JOB NOT IN ('MANAGER', 'SALESMAN', 'CLERK');
 
--5-17
SELECT *
  FROM EMP
 WHERE SAL >= 2000
   AND SAL <= 3000;
 
--5-18  BETWEEN A AND B 연산자
SELECT *
  FROM EMP
 WHERE SAL BETWEEN 2000 AND 3000; 
 
--5-19 NOT BETWEEN A AND B
SELECT *
  FROM EMP
 WHERE SAL NOT BETWEEN 2000 AND 3000;
 
--5-20 LIKE    'S%' => 대문자 S로 시작하는 데이터
SELECT *
  FROM EMP
 WHERE ENAME LIKE 'S%';
 
--5-21 LIKE   '_L%' => 2번째 글자가 L인 데이터
SELECT *
  FROM EMP
 WHERE ENAME LIKE '_L%';
 
--5-22 LIKE '%AM%' => AM이 포함되어 있는 데이터
SELECT *
  FROM EMP
 WHERE ENAME LIKE '%AM%';
 
--5-23 NOT LIKE  => AM이 포함되어 있지 않는 데이터
SELECT *
  FROM EMP
 WHERE ENAME NOT LIKE '%AM%'
 
--토막 상식 ESCAPE 절 (ESCAPE문자는 사용자 임의로 지정 가능)
--  A_A로 시작하는 데이터를 찾는 부분
SELECT *
  FROM SOME_TABLE
 WERE SOME_COLUMN LIKE 'A\_A%' ESCAPE 'W';
 
--5-25 아래의 연산자로는 NULL인 행을 찾을 수 없음
SELECT *
  FROM EMP
 WHERE COMM = NULL;
 
--5-26 IS NULL 연산자
SELECT *
  FROM EMP
 WHERE COMM IS NULL;
 
--5-27 직속 상관이 있는 사원 데이터만 출력하기
SELECT *
  FROM EMP
 WHERE MGR IS NOT NULL;
 
--5-28 AND 연산자와 IS NULL 연산자
SELECT *
  FROM EMP
 WHERE SAL > NULL
   AND COMM IS NULL;
 
--5-29 AND 연산자와 IS NULL 연산자
SELECT *
  FROM EMP
 WHERE SAL > NULL
    OR COMM IS NULL;
    
--5-30 집합 연산자(UNION)을 사용하여 출력하기
SELECT EMPNO,ENAME, SAL, DEPTNO
  FROM EMP
 WHERE DEPTNO = 10
UNION
SELECT EMPNO, ENAME, SAL, DEPTNO
  FROM EMP
 WHERE DEPTNO = 20;
 
--5-31 SELECT 문의 출력 열 개수가 다를 때(오류 남)
SELECT EMPNO, ENAME, SAL, DEPTNO
  FROM EMP
 WHERE DEPTNO = 10
UNION
SELECT EMPNO, ENAME, SAL
  FROM EMP
 WHERE DEPTNO = 20; 

--5-32 SELECT 문의 출력 열의 자료형이 다를 때(오류 남)
SELECT EMPNO, ENAME, SAL, DEPTNO
  FROM EMP
 WHERE DEPTNO = 10
UNION
SELECT ENAME, EMPNO, DEPTNO, SAL
  FROM EMP
 WHERE DEPTNO = 20;
 
--5-33 출력 열 개수와 자료형이 같을 떼
--(열 이름은 맨 앞에 작성한 SELECT절의 열 이름을 사용)
SELECT EMPNO, ENAME, SAL, DEPTNO
  FROM EMP
 WHERE DEPTNO = 10
UNION
SELECT SAL, JOB, DEPTNO, SAL
  FROM EMP
 WHERE DEPTNO = 20;
 
 
--5-34 출력 결과 데이터가 같을 때 UNION
SELECT EMPNO, ENAME, SAL, DEPTNO
  FROM EMP
 WHERE DEPTNO = 10
UNION
SELECT EMPNO, ENAME, SAL, DEPTNO
  FROM EMP
 WHERE DEPTNO = 10;
 
--5-35 출력 결과 데이터가 같을 때 UNION ALL
SELECT EMPNO, ENAME, SAL, DEPTNO
  FROM EMP
 WHERE DEPTNO = 10
UNION ALL
SELECT EMPNO, ENAME, SAL, DEPTNO
  FROM EMP
 WHERE DEPTNO = 10;
 
--5-36 MINUS연산자 ( DEPTNO가 10, 20인 데이터를 제외)
SELECT EMPNO, ENAME, SAL, DEPTNO
  FROM EMP
MINUS
SELECT EMPNO, ENAME, SAL, DEPTNO
  FROM EMP
 WHERE DEPTNO = 10
MINUS
SELECT EMPNO, ENAME, SAL, DEPTNO
  FROM EMP
 WHERE DEPTNO = 20;
 
--5-37 INTERSECT 연산자 ( 교집합)
SELECT EMPNO, ENAME, SAL, DEPTNO
  FROM EMP
INTERSECT
SELECT EMPNO, ENAME, SAL, DEPTNO
  FROM EMP
 WHERE DEPTNO = 10;
 