--Q1 사원 이름(ENAME)이 S로 끝나는 사원 데이터를 모두 출력
SELECT *
  FROM EMP
 WHERE ENAME LIKE '%S';
 
--Q2 
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
  FROM EMP
 WHERE DEPTNO = 30 
   AND JOB ='SALESMAN';
   
--Q3-1 집합 연산자를 사용하지 않은 방식 
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
  FROM EMP
 WHERE DEPTNO = 20 AND SAL > 2000
    OR DEPTNO = 30 AND SAL > 2000;
--IN 연산자를 사용해서 써도 좋음


--Q3-2 집합 연산자를 사용한 방식
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
  FROM EMP
 WHERE DEPTNO = 20
   AND SAL > 2000
UNION
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
  FROM EMP
 WHERE DEPTNO = 30
   AND SAL > 2000;
   
--Q4
SELECT *
  FROM EMP
 WHERE NOT (SAL >= 2000 AND SAL <= 3000);

SELECT *
  FROM EMP
 WHERE NOT SAL >= 2000
   OR NOT SAL <= 3000;
   
--Q5  BETWEEN 문으로도 가능
SELECT ENAME, EMPNO, SAL, DEPTNO
  FROM EMP
 WHERE ENAME LIKE '%E%'
   AND DEPTNO = 30
   AND NOT (1000<SAL AND SAL<2000);
   
--Q6 IN 연산자, NOT LIKE 연산자
SELECT *
  FROM EMP
 WHERE COMM IS NULL
   AND MGR IS NOT NULL
   AND (JOB = 'MANAGER' OR JOB='CLERK')
   AND NOT ENAME LIKE '_L%';