--주석 처리는 Ctrl+B, 주석처리 해제는 Ctrl+Shift+B
--Q2
--SELECT DISTINCT JOB
--  FROM EMP;

--Q3
SELECT EMPNO AS EMPLOYEE_NO, 
       ENAME AS EMPLOYEE_NAME,
       MGR AS MANAGER,
       SAL AS SALARY,
       COMM AS COMMISSION,
       DEPTNO AS DEPARTMENT_NO
  FROM EMP
 ORDER BY DEPTNO DESC, EMPLOYEE_NAME
  


  
